language: python
cache: pip

services:
  - postgresql
  - mysql

python:
  - 3.6
  - 3.5

env:
  matrix:
    - TOXENV=django111-sqlite
    - TOXENV=django21-sqlite
    # djangodev-sqlite requires a newer image, see below.

    - TOXENV=django111-postgres DATABASE_URL=postgres://postgres@localhost:5432
    - TOXENV=django21-postgres DATABASE_URL=postgres://postgres@localhost:5432
    - TOXENV=django22-postgres DATABASE_URL=postgres://postgres@localhost:5432
    - TOXENV=djangodev-postgres DATABASE_URL=postgres://postgres@localhost:5432

    - TOXENV=django111-mysql DATABASE_URL=mysql://root@localhost:3306
    - TOXENV=django21-mysql DATABASE_URL=mysql://root@localhost:3306
    - TOXENV=django22-mysql DATABASE_URL=mysql://root@localhost:3306
    - TOXENV=djangodev-mysql DATABASE_URL=mysql://root@localhost:3306

stages:
  - test
  - name: deploy
    if: tag IS present

install:
  - pip install tox codecov

script:
  - tox

after_script:
  - codecov

jobs:
  include:
    # These two require a newer sqlite, which requires xenial
    - python: 3.5
      dist: xenial
      env: TOXENV=django22-sqlite
    - python: 3.6
      dist: xenial
      env: TOXENV=django22-sqlite

    - python: 3.5
      dist: xenial
      env: TOXENV=djangodev-sqlite
    - python: 3.6
      dist: xenial
      env: TOXENV=djangodev-sqlite
    - python: 3.7
      dist: xenial
      env: TOXENV=djangodev-sqlite

    - python: 3.7
      dist: xenial
      env: TOXENV=live
    - python: 3.7
      dist: xenial
      env: TOXENV=flake8
    - python: 3.7
      dist: xenial
      env: TOXENV=docs

    - python: 3.7
      dist: xenial
      env: TOXENV=django11-sqlite
    - python: 3.7
      dist: xenial
      env: TOXENV=django21-sqlite
    - python: 3.7
      dist: xenial
      env: TOXENV=django22-sqlite
    - python: 3.7
      dist: xenial
      env: TOXENV=djangodev-sqlite

    - stage: deploy
      script:
        - pip install wheel twine
        - python setup.py sdist bdist_wheel
        - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
    - stage: deploy
      script:
        - pip install wheel
        - python setup.py sdist bdist_wheel
        - gem install dpl
        - dpl --api-key=$RELEASES_TOKEN --provider=releases --file=dist/* --file_glob=true --skip_cleanup=true
